services:
  backend:
    build:
      args:
        - ENVIRONMENT=local
    environment:
      - ENVIRONMENT=local
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - DEBUG=1
    ports:
      - "8000:8000"
    command: python budget/manage.py runserver 0.0.0.0:8000

  frontend:
    ports:
      - "8501:8501"
    environment:
      - ENVIRONMENT=local
      - BACKEND_URL=http://backend:8000/api

  db:
    environment:
      - POSTGRES_DB=budget
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"
  
  # celery:
  #   build:
  #     args:
  #       - ENVIRONMENT=local
  #   environment:
  #     - ENVIRONMENT=local
  #     - DJANGO_SETTINGS_MODULE=config.settings.local
  #     - DEBUG=1
  #   command: celery -A config.celery_app worker --loglevel=info
  #   depends_on:
  #     - redis
  #     - db

  qcluster:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT=local
    environment:
      - ENVIRONMENT=local
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - DEBUG=1
    command: python budget/manage.py qcluster
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
