services:
  backend:
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - DEBUG=0
    ports:
      - "8000:8000"
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    restart: always

  frontend:
    ports:
      - "8501:8501"
    environment:
      - ENVIRONMENT=production
    restart: always

  db:
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: always

  redis:
    restart: always

  celery:
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - DEBUG=0
    command: celery -A config.celery_app worker --loglevel=info
    restart: always
    depends_on:
      - redis
      - db
