# Generated by Django 5.1.4 on 2025-02-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bucket',
            unique_together=set(),
        ),
    ]
