# Generated by Django 5.1.4 on 2025-01-22 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='user_id',
            new_name='user',
        ),
    ]
