# Generated by Django 4.2.20 on 2025-04-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='allocation_percentage',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Percentage of income to allocate to this bucket', max_digits=3),
        ),
    ]
