# Generated by Django 4.2.28 on 2026-02-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_bucket_allocation_percentage'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bucket',
            index=models.Index(fields=['user', 'name'], name='bucket_user_name_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['user', 'name'], name='location_user_name_idx'),
        ),
    ]
