# Generated by Django 5.1.4 on 2025-01-23 13:00

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_user_id_bucket_user_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bucket',
            managers=[
                ('available_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='location',
            managers=[
                ('available_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
