# Generated by Django 5.1.4 on 2025-01-28 09:45

import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income'), ('Transfer', 'Transfer')], default='Expense', help_text='Transaction type', max_length=100)),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
                'ordering': ('name',),
            },
        ),
    ]
