# Generated by Django 5.1.4 on 2025-02-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Category name (e.g. (1) for Income: Salary, Bonuses, etc.; (2) for Expense: Utilities, Necessities/Utilities, Books, Education/Books, etc.', max_length=255),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='name',
            field=models.CharField(help_text='Transaction type name (e.g. Income, Expense, Transfer, etc.)', max_length=255),
        ),
    ]
