# Generated by Django 5.1.4 on 2025-01-28 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='Entry',
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('name',), 'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
    ]
