# Generated by Django 5.1.4 on 2025-02-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontype',
            name='sign',
            field=models.CharField(choices=[('POSITIVE', 'Positive amounts only (e.g. Income)'), ('NEGATIVE', 'Negative amounts only (e.g. Expense)'), ('NEUTRAL', 'Neutral/Transfer amounts (e.g. Transfer)')], default='NEUTRAL', help_text='Specifies the nature of the transactions (money coming in, going out, or moving between locations/buckets', max_length=20),
        ),
    ]
