# Generated by Django 4.2.20 on 2025-05-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='category',
            name='sign',
            field=models.CharField(choices=[('POSITIVE', 'POSITIVE'), ('NEGATIVE', 'NEGATIVE'), ('NEUTRAL', 'NEUTRAL')], default='NEUTRAL', help_text='Specifies the nature of the transactions. POSITIVE: money coming in, NEGATIVE: money going out, or NEUTRAL: moving between locations/buckets.', max_length=20),
        ),
        migrations.DeleteModel(
            name='TransactionType',
        ),
    ]
