# Generated by Django 5.1.4 on 2025-02-18 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='parent_transaction',
            field=models.ForeignKey(blank=True, help_text='Parent transaction for a split positive transaction.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='split_transactions', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='split_income',
            field=models.BooleanField(default=True, help_text='Whether to split income into multiple buckets or not (only for positive transactions).'),
        ),
    ]
