# Generated by Django 4.2.28 on 2026-02-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_category_transaction_type_category_sign_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'name'], name='category_user_name_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['sign'], name='category_sign_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date'], name='transaction_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category'], name='transaction_category_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['location'], name='transaction_location_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['bucket'], name='transaction_bucket_idx'),
        ),
    ]
