# Generated by Django 5.1.4 on 2025-02-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transactiontype_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontype',
            name='sign',
            field=models.CharField(choices=[('POSITIVE', '(+) POSITIVE amounts only (e.g. Income)'), ('NEGATIVE', '(-) NEGATIVE amounts only (e.g. Expense)'), ('NEUTRAL', '(0) NEUTRAL amounts (e.g. Transfer)')], default='NEUTRAL', help_text='Specifies the nature of the transactions (money coming in, going out, or moving between locations/buckets.', max_length=20),
        ),
    ]
