# Generated by Django 5.1.4 on 2025-02-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transactiontype_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontype',
            name='sign',
            field=models.CharField(choices=[('POSITIVE', 'POSITIVE'), ('NEGATIVE', 'NEGATIVE'), ('NEUTRAL', 'NEUTRAL')], default='NEUTRAL', help_text='Specifies the nature of the transactions (POSITIVE: money coming in, NEGATIVE: going out, or NEUTRAL: moving between locations/buckets.', max_length=20),
        ),
    ]
