# Generated by Django 5.1.4 on 2025-02-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transaction_split_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='split_income',
            field=models.BooleanField(default=False, help_text='Whether to split income into multiple buckets or not (only for positive transactions).'),
        ),
    ]
