# Generated by Django 5.1.4 on 2025-01-28 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_bucket_managers_alter_location_managers'),
        ('transactions', '0005_remove_category_user_alter_category_bucket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='bucket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.bucket'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Category name (e.g. (1) for Income: Salary, Bonuses, etc.; (2) for Expense: Utilities, Necessities/Utilities, Books, Education/Books, etc.', max_length=255, unique=True),
        ),
    ]
