# Generated by Django 5.1.4 on 2025-02-18 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_transaction_split_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 18, 13, 10, 27, 344789), help_text='Transaction date'),
        ),
    ]
