# Generated by Django 5.1.4 on 2025-01-23 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-created',), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
